# apps/datalake/layers/bronze_generator.py

from __future__ import annotations
from .bronze_inspector import DatasetSchema, ColumnInfo

# mapeamento DuckDB type → seu Field type
_TYPE_MAP = {
    "VARCHAR":   "StringField",
    "BIGINT":    "IntegerField",
    "INTEGER":   "IntegerField",
    "DOUBLE":    "DecimalField",
    "FLOAT":     "DecimalField",
    "DATE":      "DateField",
    "TIMESTAMP": "DateTimeField",
    "BOOLEAN":   "BooleanField",
    "HUGEINT":   "IntegerField",
}

def _to_field(col: ColumnInfo) -> str:
    field_cls = _TYPE_MAP.get(col.raw_type.upper(), "StringField")

    # CPF e CNPJ: detecta pelo nome da coluna
    name_lower = col.name.lower()
    if "cpf" in name_lower:
        field_cls = "CPFField"
    elif "cnpj" in name_lower:
        field_cls = "CNPJField"

    return f"    {col.name:<35} = fields.{field_cls}()"


def generate_model_code(schema: DatasetSchema, app_name: str) -> str:
    """
    Gera o código Python de um BronzeModel a partir de um DatasetSchema.
    Pronto para colar em apps/<app>/models/<modulo>.py
    """
    class_name = _to_class_name(schema.modulo)
    field_lines = "\n".join(_to_field(col) for col in schema.columns)

    return f'''\
# AUTO-GENERATED by BronzeInspector — não edite manualmente
# dataset : {schema.dataset}
# modulo  : {schema.modulo}

from apps.datalake.orm import fields
from apps.datalake.layers.bronze import BronzeModel


class {class_name}(BronzeModel):
    """
    Camada Bronze — dados crus do S3.
    Partições: modulo={schema.modulo} / ano=YYYY / mes=MM
    """

    dataset_path = "{schema.dataset}"
    modulo       = "{schema.modulo}"

    # ── Colunas (schema inferido do parquet) ──────────────────────────
{field_lines}
'''


def _to_class_name(modulo: str) -> str:
    """'gastos_diretos' → 'GastosDiretos'"""
    return "".join(part.title() for part in modulo.split("_"))