# Generated by Django 6.0.3 on 2026-03-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(help_text="Nome do dataset (ex: 'portal_da_transparencia/compras')", max_length=100, unique=True)),
                ('modulo', models.CharField(blank=True, help_text="Módulo Hive (ex: 'compras', 'licitacoes')", max_length=100)),
                ('schema', models.JSONField(help_text="Lista de colunas: [{'name': '...', 'type': 'VARCHAR', 'nullable': True}, ...]")),
                ('row_count', models.BigIntegerField(default=0, help_text='Número aproximado de linhas (baseado no sample)')),
                ('sample_values', models.JSONField(blank=True, help_text="Exemplos de valores por coluna: {'col': ['val1', 'val2', ...]}", null=True)),
                ('unique_counts', models.JSONField(blank=True, help_text="Contagem de valores únicos por coluna: {'col': 123}", null=True)),
                ('null_counts', models.JSONField(blank=True, help_text="Contagem de valores nulos por coluna: {'col': 5}", null=True)),
                ('total_files', models.IntegerField(default=0, help_text='Número total de arquivos parquet encontrados')),
                ('partitions_count', models.IntegerField(default=0, help_text='Número total de partições Hive encontradas')),
                ('last_inspection', models.DateTimeField(auto_now=True, help_text='Data da última inspeção')),
            ],
            options={
                'verbose_name': 'Metadata de Dataset',
                'verbose_name_plural': 'Metadados de Datasets',
                'indexes': [models.Index(fields=['dataset_name'], name='datalake_da_dataset_14f78b_idx'), models.Index(fields=['modulo'], name='datalake_da_modulo_4edbfe_idx')],
            },
        ),
    ]
