# Generated by Django 6.0.3 on 2026-03-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEISRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastro', models.CharField(blank=True, max_length=100)),
                ('codigo_sancao', models.CharField(blank=True, max_length=50)),
                ('categoria_sancao', models.CharField(blank=True, max_length=100)),
                ('abrangencia_sancao', models.CharField(blank=True, max_length=100)),
                ('tipo_de_pessoa', models.CharField(blank=True, max_length=1)),
                ('cpf_ou_cnpj_do_sancionado', models.CharField(blank=True, max_length=20)),
                ('nome_do_sancionado', models.CharField(blank=True, max_length=300)),
                ('nome_informado_pelo_orgao', models.CharField(blank=True, max_length=300)),
                ('razao_social_receita', models.CharField(blank=True, max_length=300, null=True)),
                ('nome_fantasia_receita', models.CharField(blank=True, max_length=300, null=True)),
                ('numero_do_processo', models.CharField(blank=True, max_length=100)),
                ('data_inicio_sancao', models.CharField(blank=True, max_length=20)),
                ('data_final_sancao', models.CharField(blank=True, max_length=20, null=True)),
                ('data_publicacao', models.CharField(blank=True, max_length=20)),
                ('data_transito_em_julgado', models.CharField(blank=True, max_length=20, null=True)),
                ('data_origem_informacao', models.CharField(blank=True, max_length=20)),
                ('publicacao', models.CharField(blank=True, max_length=200)),
                ('detalhamento_meio_publicacao', models.CharField(blank=True, max_length=300, null=True)),
                ('orgao_sancionador', models.CharField(blank=True, max_length=300)),
                ('uf_orgao_sancionador', models.CharField(blank=True, max_length=2)),
                ('esfera_orgao_sancionador', models.CharField(blank=True, max_length=50)),
                ('fundamentacao_legal', models.CharField(blank=True, max_length=500)),
                ('origem_informacoes', models.CharField(blank=True, max_length=200)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CEIS — Registro',
                'verbose_name_plural': 'CEIS — Registros',
                'db_table': 'ceis_records',
            },
        ),
    ]
