# Generated by Django 6.0.3 on 2026-03-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_da_transparencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceisrecord',
            name='abrangencia_sancao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ceisrecord',
            name='cadastro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ceisrecord',
            name='categoria_sancao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ceisrecord',
            name='codigo_sancao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ceisrecord',
            name='cpf_ou_cnpj_do_sancionado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ceisrecord',
            name='data_inicio_sancao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ceisrecord',
            name='data_origem_informacao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ceisrecord',
            name='data_publicacao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ceisrecord',
            name='esfera_orgao_sancionador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ceisrecord',
            name='fundamentacao_legal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ceisrecord',
            name='nome_do_sancionado',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ceisrecord',
            name='nome_informado_pelo_orgao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ceisrecord',
            name='numero_do_processo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ceisrecord',
            name='orgao_sancionador',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ceisrecord',
            name='origem_informacoes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ceisrecord',
            name='publicacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ceisrecord',
            name='tipo_de_pessoa',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ceisrecord',
            name='uf_orgao_sancionador',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
