# Generated by Django 6.0.3 on 2026-03-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_da_transparencia', '0002_alter_ceisrecord_abrangencia_sancao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPGFRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_orgao_superior', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_orgao_superior', models.CharField(blank=True, max_length=300, null=True)),
                ('codigo_orgao', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_orgao', models.CharField(blank=True, max_length=300, null=True)),
                ('codigo_unidade_gestora', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_unidade_gestora', models.CharField(blank=True, max_length=300, null=True)),
                ('ano_extrato', models.CharField(blank=True, max_length=4, null=True)),
                ('mes_extrato', models.CharField(blank=True, max_length=2, null=True)),
                ('cpf_portador', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_portador', models.CharField(blank=True, max_length=300, null=True)),
                ('cnpj_ou_cpf_favorecido', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_favorecido', models.CharField(blank=True, max_length=300, null=True)),
                ('transacao', models.TextField(blank=True, null=True)),
                ('data_transacao', models.CharField(blank=True, max_length=20, null=True)),
                ('valor_transacao', models.CharField(blank=True, max_length=50, null=True)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CPGF — Registro',
                'verbose_name_plural': 'CPGF — Registros',
                'db_table': 'cpgf_records',
            },
        ),
    ]
