# Generated by Django 6.0.3 on 2026-03-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_da_transparencia', '0004_viagensrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprasRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_orgao', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_orgao', models.CharField(blank=True, max_length=300, null=True)),
                ('codigo_ug', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_ug', models.CharField(blank=True, max_length=300, null=True)),
                ('numero_contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_item_compra', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao_item_compra', models.CharField(blank=True, max_length=500, null=True)),
                ('descricao_complementar_item_compra', models.TextField(blank=True, null=True)),
                ('quantidade_item', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_item', models.CharField(blank=True, max_length=50, null=True)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compras — Registro',
                'verbose_name_plural': 'Compras — Registros',
                'db_table': 'compras_records',
            },
        ),
        migrations.CreateModel(
            name='LicitacoesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_licitacao', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_processo', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_modalidade_compra', models.CharField(blank=True, max_length=10, null=True)),
                ('modalidade_compra', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_orgao', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_orgao', models.CharField(blank=True, max_length=300, null=True)),
                ('codigo_ug', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_ug', models.CharField(blank=True, max_length=300, null=True)),
                ('codigo_item_compra', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao_item_compra', models.CharField(blank=True, max_length=500, null=True)),
                ('codigo_participante', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_participante', models.CharField(blank=True, max_length=300, null=True)),
                ('flag_vencedor', models.CharField(blank=True, max_length=10, null=True)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Licitações — Registro',
                'verbose_name_plural': 'Licitações — Registros',
                'db_table': 'licitacoes_records',
            },
        ),
    ]
